### ISSUE TITLE
Split in several modules

### ISSUE THREAD

**Issue by nlepage** [Zenika/immutadot#78]
- [x] Put the lodash functions in a different module in the form of a plugin (in a different repository) #138
- [x] Have an immutadot core with no peer dependency on lodash #143
- [x] Add more plain JS functions to immutadot core (Array.push, Object.assign, etc.) #165
- [x] Update documentation to reflect the new organization -> #183

**Comment by frinyvonnick** [comment]
Maybe we should use [lerna](https://github.com/lerna/lerna) to keep a monorepo and take benefits of the multiple packages architecture.

**Comment by nlepage** [comment]
OK lerna seems to be good fit for the project, multirepo wouldn't bring any benefits in comparison.
